### ISSUE TITLE
Make models (draft, needs discussion)

### ISSUE THREAD

**Issue by bnsmth235** [Darkmono112/Hacksmith2023#14]
Note: The UML is great, but we don't need all of those things to be models, and there are some things that I think we would need as models. I described them below.

Description:
As a developer, I would like to have all the models that we were planning on put into models.py. This will help me in the future as we deal with the database and data manipulation. 

Definition of Done:
- Models are created with parameters:
    - [ ] Drone
        - [ ]  user_id = Foreign Key? If we're creating users using Django's builtin auth system, I think there would be a way to do this without creating a User model. Same for all models with a user_id
        - [ ] size = integer --> default?
        - [ ] active _status = string? wouldn't this be a bool?
        - [ ] on_order = bool
     - [ ] Order
         - [ ] user_id = Foreign key
         - [ ] drone_id = Foreign key
     - [ ] Order_Item
         - [ ] order_id = Foreign key 
         - [ ] flavor = string? --> We can have a hard coded list of options to choose from or we would use inventory objects and count unique flavors.
         - [ ] scoops = int --> Different number of scoops per cone? or just one scoop per cone. I can't remember.
         - [ ] cone = int --> I don't remember if this was a thing either, but we could have an enum for sugar, cake, and waffle cones? 
         - [ ] price = int --> int so we don't accidentally loose cents. We can either use this here or create models for cones, flavors, etc and then calculate it

**Comment by Darkmono112** [comment]
Note, Changes have been made to this ticket
