### ISSUE TITLE
Admin page is populated with items from database

### ISSUE THREAD

**Issue by zanehirning** [Darkmono112/Hacksmith2023#40]
As a admin, I would like to be able to view my current inventory

DoD:
- Order items render into table from database
- All order items data is rendered properly
- Implement a way to order more items. Ordered items are updated correctly in the database

Notes:
We will need a way to order more items. I am assuming this will be either on this page, or linked from this page.

**Comment by paigem33** [comment]
It could be nice to mimic what the drone page has as far as ordering a new inventory item, and maybe for ordering items of an existing row we could redirect to a new page with a form

**Comment by paigem33** [comment]
Basically a copy of #23 with more detail

**Comment by zanehirning** [comment]
Ben Hamner and I decided to go with a popup modal. You can see/test this on "admin-view-refactor" branch. You will need to populate the db as we do not have a migration script (or seeder).
